In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E:\datasets\houseprice.csv", usecols = ["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"])

In [3]:
df

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0             60       RL         65.0     8450   Pave      Reg       2003   
1             20       RL         80.0     9600   Pave      Reg       1976   
2             60       RL         68.0    11250   Pave      IR1       2001   
3             70       RL         60.0     9550   Pave      IR1       1915   
4             60       RL         84.0    14260   Pave      IR1       2000   
...          ...      ...          ...      ...    ...      ...        ...   
1455          60       RL         62.0     7917   Pave      Reg       1999   
1456          20       RL         85.0    13175   Pave      Reg       1978   
1457          70       RL         66.0     9042   Pave      Reg       1941   
1458          20       RL         68.0     9717   Pave      Reg       1950   
1459          20       RL         75.0     9937   Pave      Reg       1965   

      1stFlrSF  2ndFlrSF  SalePrice  
0          856       854     208500  
1         1262         0     181500  
2          920       866     223500  
3          961       756     140000  
4         1145      1053     250000  
...        ...       ...        ...  
1455       953       694     175000  
1456      2073         0     210000  
1457      1188      1152     266500  
1458      1078         0     142125  
1459      1256         0     147500  

[1460 rows x 10 columns]

In [4]:
df.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage    259
LotArea          0
Street           0
LotShape         0
YearBuilt        0
1stFlrSF         0
2ndFlrSF         0
SalePrice        0
dtype: int64

In [5]:
df.dropna(inplace = True)

In [6]:
df.isnull().sum()

MSSubClass     0
MSZoning       0
LotFrontage    0
LotArea        0
Street         0
LotShape       0
YearBuilt      0
1stFlrSF       0
2ndFlrSF       0
SalePrice      0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [8]:
#finding unique values in each columns
for col in df.columns:
    if df[col].dtype == 'object':
        print(f"The number of unique values in : '{col}' are : {df[col].nunique()}")

The number of unique values in : 'MSZoning' are : 5
The number of unique values in : 'Street' are : 2
The number of unique values in : 'LotShape' are : 4


# Feature engineering

In [9]:
import datetime

In [10]:
#calculating the age of the house by deviding todays date and the build year
today = datetime.datetime.now().year
today

2025

In [11]:
df['TotalYear'] = today - df['YearBuilt']

In [12]:
#drop year built column
df.drop('YearBuilt',axis = 1, inplace = True)

In [13]:
df

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0             60       RL         65.0     8450   Pave      Reg       856   
1             20       RL         80.0     9600   Pave      Reg      1262   
2             60       RL         68.0    11250   Pave      IR1       920   
3             70       RL         60.0     9550   Pave      IR1       961   
4             60       RL         84.0    14260   Pave      IR1      1145   
...          ...      ...          ...      ...    ...      ...       ...   
1455          60       RL         62.0     7917   Pave      Reg       953   
1456          20       RL         85.0    13175   Pave      Reg      2073   
1457          70       RL         66.0     9042   Pave      Reg      1188   
1458          20       RL         68.0     9717   Pave      Reg      1078   
1459          20       RL         75.0     9937   Pave      Reg      1256   

      2ndFlrSF  SalePrice  TotalYear  
0          854     208500         22  
1            0     181500         49  
2          866     223500         24  
3          756     140000        110  
4         1053     250000         25  
...        ...        ...        ...  
1455       694     175000         26  
1456         0     210000         47  
1457      1152     266500         84  
1458         0     142125         75  
1459         0     147500         60  

[1201 rows x 10 columns]

In [14]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'TotalYear'],
      dtype='object')

In [15]:
#encoding of categorical features
cat_features = ['MSSubClass','MSZoning', 'Street', 'LotShape'] 

# for col in df.columns:
#     if df[col].dtype == 'object':
#         cat_features.append(col)
# print(cat_features)

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encoder = LabelEncoder()
for feature in cat_features:
    df[feature] = encoder.fit_transform(df[feature])

In [18]:
print("After encoding of categorical features:\n")
df.head()

After encoding of categorical features:



MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  TotalYear  
0       854     208500         22  
1         0     181500         49  
2       866     223500         24  
3       756     140000        110  
4      1053     250000         25

# staking categorical fratues and converting into tensors

stacking and creating tensors seperataly because we should not set cat features to floot the should be int and the continous or numerical features should be float

In [19]:

import numpy as np
categorical_feat = np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
categorical_feat

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [20]:
import torch
cat_features = torch.tensor(categorical_feat, dtype = torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [22]:
#craeting continous variables to stasck and tensors
#apart from all cat features and the target consider remaing
cont_features = []
for col in df.columns:
    if col in ['MSSubClass','MSZoning', 'Street', 'LotShape','SalePrice']:
        pass
    else:
        cont_features.append(col)

print(cont_features)

cont_features = np.stack([df[i].values for i in cont_features], axis =1 )
cont_values = torch.tensor(cont_features, dtype = torch.float)
print(cont_values)
print(cont_values.dtype)

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'TotalYear']
tensor([[   65.,  8450.,   856.,   854.,    22.],
        [   80.,  9600.,  1262.,     0.,    49.],
        [   68., 11250.,   920.,   866.,    24.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    84.],
        [   68.,  9717.,  1078.,     0.,    75.],
        [   75.,  9937.,  1256.,     0.,    60.]])
torch.float32


In [26]:
### create tensor for dependent or trget variable
y = torch.tensor(df['SalePrice'], dtype = torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int32  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int32  
 5   LotShape     1201 non-null   int32  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   TotalYear    1201 non-null   int64  
dtypes: float64(1), int32(3), int64(6)
memory usage: 121.4 KB


In [28]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [39]:
cat_dim = [df[x].nunique() for x in ['MSSubClass','MSZoning', 'Street', 'LotShape']]

In [40]:
cat_dim

[15, 5, 2, 4]

In [42]:
#embading cat fet it shpuld be num_unique +1 / 2
embading_dim = [(x,min(50,(x+1)//2)) for x in cat_dim]

In [43]:
embading_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]