## NumPy Tasks

#### Basic Operations

* Create a 5×5 NumPy array filled with random numbers between 0 and 1.
* Normalize an array (i.e., scale values between 0 and 1).
* Replace all even numbers in an array with -1.
* Generate a 10×10 identity matrix.
* Find the mean, median, variance, and standard deviation of a NumPy array.
#### Indexing & Manipulation
* Extract all odd numbers from a NumPy array.
* Reshape a 1D array into a 3D array.
* Find the indices where a NumPy array’s values are greater than a given threshold.
* Stack two NumPy arrays horizontally and vertically.
* Flatten a multi-dimensional array.


In [2]:
import numpy as np

## Basic Operations

In [3]:
# Create a 5×5 NumPy array filled with random numbers between 0 and 1.
np.random.seed(42)
np.random.rand(5,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [9]:
# Normalize an array (i.e., scale values between 0 and 1).
X = np.random.randint(10,100,10)
Xmax = arr.max()
Xmin = arr.min()
normalize = (X - Xmin) / (Xmax - Xmin)
normalize

array([0.06818182, 0.51136364, 0.375     , 0.86363636, 0.89772727,
       0.38636364, 0.54545455, 0.02272727, 0.        , 0.04545455])

In [26]:
# Replace all even numbers in an array with -1
x = np.arange(1,10)
x[x % 2 == 0] = -1
x

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])

In [27]:
# Generate a 10×10 identity matrix.
#Using np.eye() (Identity Matrix)
x = np.eye(10)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
# Find the mean, median, variance, and standard deviation of a NumPy array.
x = np.arange(1,21)
Xmean = np.mean(x)
Xmedian = np.median(x)
Xvar = np.var(x)
Xsd = np.std(x)

print("mean              :",Xmean)
print("median            :",Xmedian)
print("variance          :",Xvar)
print("standard deviation:",Xsd)

mean              : 10.5
median            : 10.5
variance          : 33.25
standard deviation: 5.766281297335398


## Indexing & Manipulation

In [82]:
# Extract all odd numbers from a NumPy array.

x = np.arange(0,10)
x[x % 2 != 0] 

array([1, 3, 5, 7, 9])

In [83]:
# Reshape a 1D array into a 3D array.
arr = np.arange(0,12)
arr.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [84]:
# Find the indices(indexes) where a NumPy array’s values are greater than a given threshold.
threshold = 20
x = np.arange(1,25)
print("Indices: ",np.where(x > threshold)) # returns indices(indexes)
print("values: ",x[x > threshold])

Indices:  (array([20, 21, 22, 23], dtype=int64),)
values:  [21 22 23 24]


In [85]:
# Stack two NumPy arrays horizontally and vertically.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
hstack = np.hstack((arr1, arr2)) # horizontal stack
vstack = np.vstack((arr1, arr2)) # vertical stack
print(hstack,'\n',vstack)

[1 2 3 4 5 6] 
 [[1 2 3]
 [4 5 6]]


In [86]:
# Flatten a multi-dimensional array.
x = np.random.rand(3,3,2)
x.flatten()

array([0.64517279, 0.17436643, 0.69093774, 0.38673535, 0.93672999,
       0.13752094, 0.34106635, 0.11347352, 0.92469362, 0.87733935,
       0.25794163, 0.65998405, 0.8172222 , 0.55520081, 0.52965058,
       0.24185229, 0.09310277, 0.89721576])