# NumPy Copy and View of Array

While working with NumPy, you might have seen some functions return the copy whereas some functions return the view.

The main difference between copy and view is that the copy is the new array whereas the view is the view of the original array. In other words, it can be said that the copy is physically stored at another location and the view has the same memory location as the original array

In [3]:
import numpy as np

In [19]:
#Example 1: Making a view and changing the original array
#create array
arr = np.array([1,10,21,32])
#create view
v = arr.view()

# both arr and v have different id  
print("id of arr: ", id(arr))  
print("id of v  : ", id(v))  

id of arr:  2202931408176
id of v  :  2202954091664


In [21]:
# changing original array  
# will effect view
arr[0] = 1112
print("view after changing value in array: ",v)

view after changing value in array:  [1112   10   21   32]


-------------------------------------------------------------------------------------------------------------------------------

In [24]:
#Example 2: Making a copy and changing the original array
#create array
arr = np.array([1,10,21,32])

#create copy
c = arr.copy()
# printing array and copy 
print("original array:", arr) 
print("copy          :", c) 

original array: [ 1 10 21 32]
copy          : [ 1 10 21 32]


In [27]:
# changing original array 
# this will not effect copy 
arr[0] = 10
print("original array:", arr)
print("copy          :", c) 

original array: [10 10 21 32]
copy          : [ 1 10 21 32]


--------------------------------------------------------------------------------------------------------------------------

In [28]:
#Example 3: Check if the array is a view or copy
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# creating copy of array 
c = arr.copy() 

# creating view of array 
v = arr.view() 

# printing base attribute of copy and view 
print(c.base) 
print(v.base) 


None
[ 2  4  6  8 10]


########################################################################################################################################################

## Copy NumPy Array into Another Array

- Using np.copy() Function
- 
Copy Given 2-D Array to Another Array

**Copy 1D Numpy Arrays into Another Using np.copy() Function**

In the below example, the given Numpy array ‘org_array‘ is copied to another array ‘copy_array‘ using np.copy () function.

In [30]:
# importing Numpy package
import numpy as np

# Creating a numpy array using np.array()
org_array = np.array([1.54, 2.99, 3.42, 4.87, 6.94,
					8.21, 7.65, 10.50, 77.5])

print("Original array: ")

# printing the Numpy array
print(org_array)

# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)

print("\nCopied array: ")

# printing the copied Numpy array
print(copy_array)


Original array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]

Copied array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]


--------------------------------------------------------------------------------------------------------------------------------------------------

**Copy Given 2-D Array to Another Array Using np.copy() Function**
    
In this example, the given 2-D Numpy array ‘org_array‘ is copied to another array ‘copy_array‘ using np.copy () function.

In [31]:
# importing Numpy package
import numpy as np

# Creating a 2-D numpy array using np.array()
org_array = np.array([[23, 46, 85],
					[43, 56, 99],
					[11, 34, 55]])

print("Original array: ")

# printing the Numpy array
print(org_array)

# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)

print("\nCopied array: ")

# printing the copied Numpy array
print(copy_array)


Original array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]

Copied array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]


--------------------------------------------------------------------------------------------------------------------------------------------------

**NumPy Array Copy Using Assignment Operator**

In the below example, the given Numpy array ‘org_array‘ is copied to another array ‘copy_array‘ using Assignment Operator.

In [32]:
# importing Numpy package
import numpy as np

# Create a 2-D Numpy array using np.array()
org_array = np.array([[99, 22, 33],
					[44, 77, 66]])

# Copying org_array to copy_array
# using Assignment operator
copy_array = org_array

# modifying org_array
org_array[1, 2] = 13

# checking if copy_array has remained the same

# printing original array
print('Original Array: \n', org_array)

# printing copied array
print('\nCopied Array: \n', copy_array)


Original Array: 
 [[99 22 33]
 [44 77 13]]

Copied Array: 
 [[99 22 33]
 [44 77 13]]


#############################################################################################################################################

# Appending values at the end of an NumPy array

**Appending Values at the End of an NumPy Array**

- Appending a Single Value to a 1D Array
- Appending Another Array at the End of a 1D Array
- Appending Values at the End Using Concatenation
- Appending with a Different Array Type
- Appending Using List Comprehension and numpy.concatenate
- Appending Values at the End of the N-Dimensional Array

**Appending a Single Value to a 1D Array**

For a 1D array, using the axis argument is not necessary as the array is flattened by default.

In [35]:
arr = np.array([1,2,3,4,5,6])
print("Original array: ",arr)

#appending new value
arr = np.append(arr,[7])
print("new array     : ",arr)

Original array:  [1 2 3 4 5 6]
new array     :  [1 2 3 4 5 6 7]


-----------------------------------------------------------------------------------------------------------------------------------------------

**Appending Another Array at the End of a 1D Array**

You may pass a list or an array to the append function, the result will be the same

In [46]:
# creating an array
arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)
 
# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)

# appending arr2 to arr1
arr = np.append(arr2,arr1)
arr

First array is :  [1 2 3]
Second array is :  [4 5 6]


array([4, 5, 6, 1, 2, 3])

------------------------------------------------------------------------------------------------------------------------------------------------

**Appending Values at the End Using Concatenation**
    
In this example, two 2D arrays, arr1 and arr2, are vertically stacked using np.concatenate() along the 0th axis, resulting in a combined 2D array.

In [51]:
#creating arr1 and arr2
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[8,9]])

#concatinating arr1 and arr2
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [8 9]]


------------------------------------------------------------------------------------------------------------------------------------------------

**Appending with a Different Array Type**

In this example, a 1D integer array arr and a 1D float array arr_float are appended together using np.append(), resulting in an upcasted float array as the output.

In [54]:
# importing the module
import numpy as np

arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

combined = np.append(arr, arr_float)
print(combined) # Output: [1. 2. 3. 4. 5.]


[1. 2. 3. 4. 5.]


----------------

**Appending Using List Comprehension and numpy.concatenate**

In [56]:
# importing the module
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
values_to_append = [np.array([6, 7]), np.array([8, 9])]
combined = np.concatenate([arr] + values_to_append)
print(combined)


[1 2 3 4 5 6 7 8 9]


**Appending Values at the End of the N-Dimensional Array**
    
It is important that the dimensions of both the array matches otherwise it will give an error.

In [68]:
# importing the module
import numpy as np

# create an array
arr = np.arange(1,13).reshape(2,6)
print("Original array:\n",arr)

#create array to be added column wise
arr1 = np.arange(5,11).reshape(1,6)
print("\narray to be added row wise:\n",arr1)

#append arr and arr1 column wise
arr_col = np.concatenate((arr,arr1),axis=0)
print("\nappended arr and arr1 column wise:\n",arr_col)

#create array to be added row wise
arr2 = np.arange(1,3).reshape(2,1)
print("\narray to be added column wise:\n",arr2)

#append arr and arr2 row wise
arr_row = np.concatenate((arr,arr2),axis=1)
print("\nappended arr and arr1 row wise:\n",arr_row)


Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

array to be added row wise:
 [[ 5  6  7  8  9 10]]

appended arr and arr1 column wise:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]]

array to be added column wise:
 [[1]
 [2]]

appended arr and arr1 row wise:
 [[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


###################################################################################################################################

# swap columns of a given NumPy array

**Approach :**

- Import NumPy module
- Create a NumPy array
- Swap the column with Index
- Print the Final array

In [88]:
#Example 1: Swapping the column of an array. 
arr = np.arange(12).reshape(4,3)
print("Original array:\n",arr)

# swapping the column with index of 
arr[:,[2,0]] = arr[:,[0,2]]

print("\nAfter swapping arrays the last column and first column:\n",arr)

Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

After swapping arrays the last column and first column:
 [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


---

In [100]:
#Example 2: Swapping the column of an array with the user chooses.
def swap_array(arr,start_index,last_index):
    arr[:,[start_index,last_index]] = arr[:,[last_index,start_index]]



arr = np.arange(12).reshape(4,3)
print("Original array:\n",arr)
swap_array(arr, 1,2)
print("\narray after swapping:\n",arr)

Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

array after swapping:
 [[ 0  2  1]
 [ 3  5  4]
 [ 6  8  7]
 [ 9 11 10]]


##################################################################################################################################################

**This post deals with the ways to increase the dimension of an array in NumPy. NumPy provides us with two different built-in functions to increase the dimension of an array i.e.**

- 1D array will become 2D array
- 2D array will become 3D array
- 3D array will become 4D array
- 4D array will become 5D array
- 
**Add a New Axis to a Numpy Array**
  
There are various ways to add a new axis to a NumPy array, here we are discussing some generally used methods for adding a new axis to a numpy array those are following.

- Using numpy.newaxis()
- Using numpy.expand_dims()

- Simultaneously insert many axes in the array
- Using numpy.reshape() a Single Axis
-----------------------------------------------------------------------------------------------------------------------------------------------------
  
**1) Using numpy.newaxis()**
  
The first method is to use **numpy.newaxis** object. This object is equivalent to use None as a parameter while declaring the array. The trick is to use the numpy.newaxis object as a parameter at the index location in which you want to add the new axis.

In this example This code uses NumPy to create a 2D array ‘arr’ with shape (5, 5) containing sequential values. It then transforms ‘arr’ into a 5D array ‘arr_5D’ by adding dimensions using indexing with ‘np.newaxis’. The resulting shape of ‘arr_5D’ is (1, 5, 5, 1, 1).

In [118]:
#example 1
#create 2D array with shape 5x5
arr = np.arange(25).reshape(5,5)
print("Original array:\n",arr)
print("Shape of arr: ",arr.shape)

#adding new axis
arr_3d = arr[:,np.newaxis]
print("\n2D to 3D array:\n",arr_3d)
print("shape of arr_3d:",arr_3d.shape)

arr_4d = arr_3d[:,np.newaxis]
print("\n3D to 4D array:\n",arr_4d)
print("shape of arr_4d:",arr_4d.shape)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Shape of arr:  (5, 5)

2D to 3D array:
 [[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]

 [[20 21 22 23 24]]]
shape of arr_3d: (5, 1, 5)

3D to 4D array:
 [[[[ 0  1  2  3  4]]]


 [[[ 5  6  7  8  9]]]


 [[[10 11 12 13 14]]]


 [[[15 16 17 18 19]]]


 [[[20 21 22 23 24]]]]
shape of arr_4d: (5, 1, 1, 5)


###########################################################################################################################################

# numpy.hstack() in Python

numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [127]:
# Python program explaining 
# hstack() function ----------horizontal stack

# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [128]:
#Example 2
# input array 
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output horizontally stacked array:
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


###############################################################################################################################################

# numpy.vstack() in python

numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.

In [131]:
#Example 1
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)

out_arr = np.vstack((in_arr1,in_arr2))
print ("Output vertically stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [132]:
#Example 2
# input array 
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2) 

out_arr = np.vstack((in_arr1,in_arr2))
print ("Output vertically stacked array:\n ", out_arr) 

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output vertically stacked array:
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


##########################################################################################################################################

# Joining NumPy Array

NumPy provides various functions to combine arrays. In this article, we will discuss some of the major ones.

- numpy.concatenate
- numpy.stack
- numpy.block

**Method 1: Using numpy.concatenate()**

The concatenate function in NumPy joins two or more arrays along a specified axis. 

In [134]:
#example 1
Earray_1 = np.array([1, 2]) 
array_2 = np.array([3, 4]) 
  
array_new = np.concatenate((array_1, array_2)) 
print(array_new) 

#By default, the value of the axis is set to 0. You can change it by specifying a value for the axis in the second argument. 

[1 2 3 4]


In [137]:
#example 2: The following code joins two arrays along rows.
array_1 = np.array([[1, 2], [3, 4]]) 
array_2 = np.array([[5, 6], [7, 8]]) 

array_new = np.concatenate((array_1, array_2),axis =1)
print("joins two arrays along rows:\n",array_new) 

joins two arrays along rows:
 [[1 2 5 6]
 [3 4 7 8]]


**Method 2: Using numpy.stack()**

Syntax: numpy.stack(arrays, axis=0)

In [142]:
#example 1
array_1 = np.array([1, 2, 3, 4]) 
array_2 = np.array([5, 6, 7, 8]) 

array_new = np.stack((array_1, array_2), axis=1) 
print(array_new) 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


**Method 3: numpy.block()**

numpy.block is used to create nd-arrays from nested blocks of lists.

Syntax: numpy.block(arrays)


In [144]:
#example 1
block_1 = np.array([[1, 1], [1, 1]]) 
block_2 = np.array([[2, 2, 2], [2, 2, 2]]) 
block_3 = np.array([[3, 3], [3, 3], [3, 3]]) 
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]]) 
  
block_new = np.block([ 
    [block_1, block_2], 
    [block_3, block_4] 
]) 
  
print(block_new) 

[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]
