**NumPy Introduction & Guide for Beginners**

NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.

It also have a collection of high-level mathematical functions to operate on arra

**What is NumPy?** 

NumPy is a general-purpose array-processing package.

It provides a high-performance multidimensional array object and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It is open-source soft

**Why do we need NumPy ?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.wiety of databases.iety of databases.ys

**Features of NumPy**

NumPy has various features which make them popular over lists.

Some of these important features include:

* A powerful N-dimensional array object
* Sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Useful linear algebra, Fourier transform, and random number capabilities.
  
Besides its obvious scientific uses, NumPy in Python can also be used as an efficient multi-dimensional container of generic data.

Arbitrary data types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

**Arrays in NumPy**

NumPy’s main object is the homogeneous multidimensional array.

* It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
* In NumPy, dimensions are called axes. The number of axes is rank.
* NumPy’s array class is called ndarray. It is also known by the alias array.

**Example:**

In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes.

The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3, i.e., the number of columns. The overall shape of the array can be represented as (2, 3)

In [1]:
#import numpy
import numpy as np
# Creating array object
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr)

# Printing type of arr object
print("Type of an array is :",type(arr))

# Printing shape of array
print("Shape of an array is :",arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

[[1 2 3]
 [4 5 6]]
Type of an array is : <class 'numpy.ndarray'>
Shape of an array is : (2, 3)
Size of array:  6
Array stores elements of type:  int32


**NumPy Array Creation**

There are various ways of Numpy array creation in Python. They are as followsion:

**1. Create NumPy Array with List and Tuple**

You can create an array from a regular Python list or tuple using the array() function. The type of the resulting array is deduced from the type of the elements in the sequences. Let’s see this implementation:

In [2]:
# Creating array from list with type float
a = np.array([[1,2,3],[4,5,6]],dtype = float)
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array(((6,7,8),(8,9,10)), dtype = float)
print ("Array created using passed tuple:\n", b)

Array created using passed list:
 [[1. 2. 3.]
 [4. 5. 6.]]
Array created using passed tuple:
 [[ 6.  7.  8.]
 [ 8.  9. 10.]]


**2. Create Array of Fixed Size**

Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content.

This minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

In [3]:
# Creating a 3X4 array with all zeros
c = np.zeros((3,4), dtype = int)
print ("An array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3,3),6,dtype = 'complex')
print ("An array initialized with all 6s.Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2,2))
print ("A random array:\n", e)

An array initialized with all zeros:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.03915988 0.52626185]
 [0.01984174 0.3226864 ]]


**3. Create Using arange() Function**

arange(): This function returns evenly spaced values within a given interval. Step size is specified.

In [4]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5
f = np.arange(0,31,5)
print ("A sequential array with steps of 5: ", f)

# Create a sequence of integers  0 to 10
f = np.arange(0,11)
print ("\nA sequential array 0 to 10: ", f)

A sequential array with steps of 5:  [ 0  5 10 15 20 25 30]

A sequential array 0 to 10:  [ 0  1  2  3  4  5  6  7  8  9 10]


**4. Create Using linspace() Function**

linspace(): It returns evenly spaced values within a given interval

The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number..

**Synatx: numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)**

In [5]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0,5,10)
print ("A sequential array with 10 values between 0 and 5:\n", g)

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


**5. Reshaping Array using Reshape Method**

Reshaping array: We can use reshape method to reshape an array.

Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM. (i.e. the original size of the array remains unchanged.)

In [6]:
# Reshaping 3X4 array to 2X2X3 array

arr = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12]])

newarr = arr.reshape(2,2,3)

print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------
Reshaped array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**6. Flatten Array**

Flatten array: We can use flatten method to get a copy of the array collapsed into one dimension.

It accepts order argument. The default value is ????’ (for row-major order). Use ????’ for column-major order.

In [7]:
# Create array
arr = np.array([[1,2,3],[4,5,6]])

#flatten array
flat_arr = arr.flatten()

print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


**NumPy Array Indexing**

Knowing the basics of NumPy array indexing is important for analyzing and manipulating the array object. NumPy in Python offers many ways to do array indexing.

* Slicing: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
* 
Integer array indexing: In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding elements is done to construct a new arbitrary array
* 
Boolean array indexing: This method is used when we want to pick elements from the array which satisfy some condition.

In [8]:
# Python program to demonstrate a need of NumPy

list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]

# Multiplying both lists directly would give an error.
print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
# Python program to demonstrate the use of NumPy arrays
import numpy as np

list1 = [1, 2, 3, 4, 5, 6]
list2 = [10, 9, 8, 7, 6, 5]

# Convert list1 into a NumPy array
a1 = np.array(list1)

# Convert list2 into a NumPy array
a2 = np.array(list2)

print(a1*a2)

[10 18 24 28 30 30]


In [10]:
# Python program to demonstrate
# indexing in numpy
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2,::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


**NumPy Basic Operations**

The Plethora of built-in arithmetic functions is provided in Python NumPy.

**1. Operations on a single NumPy array**

We can use overloaded arithmetic operators to do element-wise operations on the array to create a new array. In the case of +=, -=, *= operators, the existing array is modified.




In [32]:
a = np.array([1,2,3,4,5])

#adding 1 to each ele in a
print("adding 1: ",a+1)

#substract 3 from each ele in a
print("substracting 3: ",a-3)

#multiplying each ele with 10 in a
print("multiply 10: ",a*10)

#squre each ele in a
print("squre: ",a**2)

# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

#transpose of array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array: ",a)
print("Transpose array: ",a.T)

adding 1:  [2 3 4 5 6]
substracting 3:  [-2 -1  0  1  2]
multiply 10:  [10 20 30 40 50]
squre:  [ 1  4  9 16 25]
Doubled each element of original array: [ 2  4  6  8 10]
Original array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose array:  [[1 4 7]
 [2 5 8]
 [3 6 9]]


**NumPy – Unary Operators**

Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [11]:
# Python program to demonstrate
# unary operators in numpy
import numpy as np

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

# maximum element of array
print("Largest element in array:",arr.max())
print("Row wise largest elements: ",arr.max(axis = 1))

# minimum element of array
print("\nSmallest element in array: ",arr.min())
print("Column wise smallest element: ",arr.min(axis = 0))

#sum of array elements
print("Sum of all elements in array: ",arr.sum())

# cumulative sum along each row
print("# cumulative sum along each row: ",arr.cumsum(axis = 1))

Largest element in array: 9
Row wise largest elements:  [6 7 9]

Smallest element in array:  1
Column wise smallest element:  [1 1 2]
Sum of all elements in array:  38
# cumulative sum along each row:  [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


**NumPy – Binary Operators**

These operations apply to the array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /,  etc. In the case of +=, -=, = operators, the existing array is modified.

In [12]:
# Python program to demonstrate
# binary operators in Numpy
import numpy as np

a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


**NymPy’s ufuncs**
  
NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc. 

In [13]:
# Python program to demonstrate
# universal functions in numpy
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


**NumPy Sorting Arrays**

There is a simple np.sort() method for sorting Python NumPy arrays. Let’s explore it a bit.

In [30]:
# Python program to demonstrate sorting in numpy
a = np.array([[1, 4, 2],
              [3, 4, 6],
              [0, -1, 5]])
# sorted array
print("Array elements in sorted order:\n",np.sort(a,axis = None))

# specify sort algorithm
print("Column wise sort using merge-sort :\n",np.sort(a,axis =0,kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print("Structured array:\n",arr)
print("Array sorted by name:\n",np.sort(arr, order='name'))
print("Array sorted by graduation year then cgpa:\n",np.sort(arr,order=['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Column wise sort using merge-sort :
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
Structured array:
 [(b'Hrithik', 2009, 8.5) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]
Array sorted by name:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


**Exercise**

**1. Array Creation and Initialization**

Task:

- Create a NumPy array from a list and a tuple.
- Create a 3x4 matrix of zeros and a 2x2 matrix of ones.
- Generate a sequence of numbers starting from 10 to 50 with a step size of 5, and another sequence of 10 evenly spaced numbers between 0 and 1.

*solution*

In [37]:
#1) Create a NumPy array from a list and a tuple.
a = ((1,2,3),(4,5,6))
arr_tup = np.array(a)
print("Array by tuple:\n",arr_tup)

b = [[1,2,3],[4,5,6]]
arr_list = np.array(b)
print("Array by list:\n",arr_list)

Array by tuple:
 [[1 2 3]
 [4 5 6]]
Array by list:
 [[1 2 3]
 [4 5 6]]


In [44]:
#2) Create a 3x4 matrix of zeros and a 2x2 matrix of ones.
mat_1 = np.zeros((3,4),dtype = 'int')
print("matrix of zeros:\n",mat_1)

mat_2 = np.full((2,2),1)
print("matrix of ones:\n",mat_2)

matrix of zeros:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
matrix of ones:
 [[1 1]
 [1 1]]


In [51]:
#3) Generate a sequence of numbers starting from 10 to 50 with a step size of 5, and another sequence of 10 evenly spaced numbers between 0 and 1.
a = np.arange(10,51,5)
print("sequence of numbers starting from 10 to 50 with a step size of 5:\n",a)

b = np.linspace(0,1,10)
print("\nsequence of 10 evenly spaced numbers between 0 and 1:\n",b)

sequence of numbers starting from 10 to 50 with a step size of 5:
 [10 15 20 25 30 35 40 45 50]

sequence of 10 evenly spaced numbers between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**2. Array Reshaping and Flattening**

Task:
- Given a 1D array with 12 elements, reshape it into a 3x4 matrix and then flatten it back into a 1D array.
- Reshape the same array into a 2x2x3 array.
- Describe the difference between reshaping and flattening arrays.

In [59]:
#1) Given a 1D array with 12 elements, reshape it into a 3x4 matrix and then flatten it back into a 1D array.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_arr = arr.reshape(3,4)
print("Original array:\n",arr)
print("Reshaped arra to 3x4:\n",reshape_arr)
flatten_arr = reshape_arr.flatten()
print("Converted 3x4 array to 1D array:\n",flatten_arr)

#2) Reshape the same array into a 2x2x3 array.
reshaped_arr = flatten_arr.reshape(2,2,3)
print("Reshaped arra to 2x2x3:\n",reshaped_arr)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped arra to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Converted 3x4 array to 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped arra to 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**3. Array Indexing and Slicing**

Task:

- Create a 2D array and access the element at a specific position (e.g., the second row, third column).
- Extract a specific row and column from the array.
- Slice the array to extract a subset (e.g., the first two rows and columns).
- Modify a specific element in the array and observe the changes.

In [76]:
#1) Create a 2D array and access the element at a specific position (e.g., the second row, third column).
arr = np.array([[1,2,3],[4,5,6]])
print("Original array:\n",arr)

temp = arr[1,2]
print("the second row, third column:",temp)

Original array:
 [[1 2 3]
 [4 5 6]]
the second row, third column: 6


In [81]:
#2) Slice the array to extract a subset (e.g., the first two rows and columns).
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:\n",arr)
temp = arr[:2,:2]
temp

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

**4. Mathematical Operations**

Task:

- Perform the following operations on an array of integers:
- Add a constant value to each element.
- Multiply each element by a constant.
- Square each element.
- Find the square root of each element.
- Calculate the sum, mean, and standard deviation of the array.

In [98]:
arr = np.arange(1,20,2)
print("Original Array:\n",arr)

#Add a constant value to each element.
print("\nAdding 3 to each elements in array: ",arr+3)

#Multiply each element by a constant.
print("\nMultipying each element by 10: ",arr*10)

#Square each element.
sqr = arr**2
print("\nSqure of each elements: ",sqr)

#Find the square root of each element.
print("\nSqure root of each elements in sqr: ",np.sqrt(sqr))

#Calculate the sum, mean, and standard deviation of the array.
print("\nsum of an array: ",np.sum(arr))
print("mean of an array: ",np.mean(arr))
print("standard deviation of the array: ",np.std(arr))

Original Array:
 [ 1  3  5  7  9 11 13 15 17 19]

Adding 3 to each elements in array:  [ 4  6  8 10 12 14 16 18 20 22]

Multipying each element by 10:  [ 10  30  50  70  90 110 130 150 170 190]

Squre of each elements:  [  1   9  25  49  81 121 169 225 289 361]

Squre root of each elements in sqr:  [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]

sum of an array:  100
mean of an array:  10.0
standard deviation of the array:  5.744562646538029


**5. Broadcasting**

Broadcasting is a powerful feature in NumPy that allows you to perform element-wise operations on arrays of different shapes. It "stretches" or "broadcasts" smaller arrays across larger arrays to make their shapes compatible for element-wise operations, without creating explicit copies of the data. Broadcasting works by aligning the dimensions of arrays in such a way that operations can be performed element-wise even if the shapes of the arrays don't match exactly.

Task:

- Create a 2D array and a 1D array, then perform element-wise addition and subtraction between the two.
- Multiply the 2D array by a scalar.
- Explain how broadcasting works and why it allows these operations.


In [99]:
import numpy as np

# Create a 2D array (3x3)
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Create a 1D array (with 3 elements)
arr_1d = np.array([1, 2, 3])

# Element-wise addition
result_add = arr_2d + arr_1d

# Element-wise subtraction
result_subtract = arr_2d - arr_1d

# Multiply the 2D array by a scalar (e.g., 2)
result_multiply = arr_2d * 2

print("Original 2D array:")
print(arr_2d)

print("\n1D array:")
print(arr_1d)

print("\nElement-wise addition (2D + 1D):")
print(result_add)

print("\nElement-wise subtraction (2D - 1D):")
print(result_subtract)

print("\nMultiply the 2D array by a scalar (2):")
print(result_multiply)


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D array:
[1 2 3]

Element-wise addition (2D + 1D):
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Element-wise subtraction (2D - 1D):
[[0 0 0]
 [3 3 3]
 [6 6 6]]

Multiply the 2D array by a scalar (2):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**6. Sorting Arrays**

Task:

- Sort a 1D array in ascending and descending order.
- Sort a 2D array row-wise and column-wise.
- Investigate how sorting works with negative numbers and missing values.

In [112]:
arr = np.array([1,2,8,9,7,3,5,4,0])
print("Original 1D array:",arr)
#Sort a 1D array in ascending and descending order.
print("Sorted array in ascending order: ",np.sort(arr))
print("Sorted array in descending order: ",np.sort(arr)[::-1])

#Sort a 2D array row-wise and column-wise.
arr = np.array([[5,8,9,1],[12,5,69,32]])
print("\nOriginal 2D array:\n",arr)
print("Sorted array row wise:\n",np.sort(arr,axis=1))
print("Sorted array column wise:\n",np.sort(arr,axis=0))

Original 1D array: [1 2 8 9 7 3 5 4 0]
Sorted array in ascending order:  [0 1 2 3 4 5 7 8 9]
Sorted array in descending order:  [9 8 7 5 4 3 2 1 0]

Original 2D array:
 [[ 5  8  9  1]
 [12  5 69 32]]
Sorted array row wise:
 [[ 1  5  8  9]
 [ 5 12 32 69]]
Sorted array column wise:
 [[ 5  5  9  1]
 [12  8 69 32]]


**7. Linear Algebra Operations**

Task:

- Given two square matrices, perform the following operations:
- Multiply the matrices.
- Calculate the determinant of one matrix.
- Find the inverse of a matrix if it exists.
- Compute the eigenvalues and eigenvectors of the matrix.

In [118]:
#1) Given two square matrices, perform the following operations:

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[14,15,16],[17,18,19],[11,12,13]])

#Multiply the matrices.
print("Multiply matrix a and b:\n",a*b)

#Calculate the determinant of one matrix.
determinant = np.linalg.det(a)
print("Determinant of the matrix:", determinant)

#Find the inverse of a matrix if it exists.
# Check if the determinant is non-zero (matrix is invertible)
determinant = np.linalg.det(a)
if determinant != 0:
    # Calculate the inverse
    inverse = np.linalg.inv(a)
    print("Inverse of the matrix:")
    print(inverse)
else:
    print("The matrix is singular and does not have an inverse.")

#Compute the eigenvalues and eigenvectors of the matrix.
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Multiply matrix a and b:
 [[ 14  30  48]
 [ 68  90 114]
 [ 77  96 117]]
Determinant of the matrix: -9.51619735392994e-16
Inverse of the matrix:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]

Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


**8. Array Aggregation and Comparison**

Task:

- Given a 2D array, compute the sum of all elements and the sum along each row and column.
- Find the maximum and minimum values in the array.
- Compare the array against a constant value to create a boolean array, indicating where values exceed that threshold.

In [143]:
#Given a 2D array, compute the sum of all elements and the sum along each row and column.
arr = np.array([[11,12,13],
                [21,22,23],
                [31,32,33]])
array_sum = np.sum(arr)
print("the sum of all elements: ",array_sum)

#sum along each row and column
row_sum = np.sum(arr,axis = 1)
print("\nsum along each row   : ",row_sum)
col_sum = np.sum(arr,axis = 0)
print("\nsum along each column: ",col_sum)

#Find the maximum and minimum values in the array
max_val = np.max(arr)
min_val = np.min(arr)
print("Max value in array: ",max_val)
print("Min value in array: ",min_val)

#Compare the array against a constant value to create a boolean array, indicating where values exceed that threshold.
constant = 22
bool_array = arr > constant
print("boolean array, indicating where values exceed that threshold:\n",bool_array)

the sum of all elements:  198

sum along each row   :  [36 66 96]

sum along each column:  [63 66 69]
Max value in array:  33
Min value in array:  11
boolean array, indicating where values exceed that threshold:
 [[False False False]
 [False False  True]
 [ True  True  True]]


**9. Handling Missing Data**

Task:

- Given an array with some missing values, replace the missing values with a specific value (e.g., zero).
- Calculate the mean of the array while ignoring missing values.
- Create a boolean mask identifying missing data.


In [221]:
#Given an array with some missing values, replace the missing values with a specific value (e.g., zero).
arr = np.array([[1,2,np.nan],[4,np.nan,6],[7,8,np.nan]])
print("Original array:\n",arr)

replace_arr = np.nan_to_num(arr, nan=0)
#convert float dtype to int
replace_arr = replace_arr.astype(int)
print("\nmissing values with a specific value with zero:\n",replace_arr)

#Calculate the mean of the array while ignoring missing values.
mean_arr = np.nanmean(arr)
print("\nthe mean of the array while ignoring missing values: ",mean_arr)

#Create a boolean mask identifying missing data.
bool_mis = np.isnan(arr)
print("\nboolean mask identifying missing data:\n",bool_mis)

Original array:
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8. nan]]

missing values with a specific value with zero:
 [[1 2 0]
 [4 0 6]
 [7 8 0]]

the mean of the array while ignoring missing values:  4.666666666666667

boolean mask identifying missing data:
 [[False False  True]
 [False  True False]
 [False False  True]]


**10. Random Number Generation**

Task:

- Generate a 5x5 array of random values between 0 and 1.
- Generate a 5x5 array of random integers within a specified range.
- Generate random numbers from a normal distribution with a given mean and standard deviation.
- Explain how setting a random seed affects reproducibility.

In [187]:
#Generate a 5x5 array of random values between 0 and 1.
a = np.random.rand(5,5)
print("5x5 array of random values between 0 and 1:\n",a)

#Generate a 5x5 array of random integers within a specified range
b = np.random.randint(low=10,high=20,size = (5,5))
print("\n5x5 array of random integers within a specified range:\n",b)

#Generate random numbers from a normal distribution with a given mean and standard deviation.
# Define the parameters for the normal distribution
mean = 0          # Mean (loc)
std_dev = 1       # Standard Deviation (scale)
size = (5, 5)     # Shape of the output array (5x5)

#Generate random numbers from a normal distribution
#Reproducibility:----------------------------------------------------------------------------------------------imp
#To make the random values reproducible, set a random seed:----------------------------------------------------imp
np.random.seed(42) #------------------------------- produces same values in random

random_normal_array = np.random.normal(loc=mean, scale=std_dev,size = size)
print("\nrandom numbers from a normal distribution:\n",random_normal_array)

5x5 array of random values between 0 and 1:
 [[0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998]
 [0.66252228 0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998]]

5x5 array of random integers within a specified range:
 [[17 16 18 17 14]
 [11 14 17 19 18]
 [18 10 18 16 18]
 [17 10 17 17 12]
 [10 17 12 12 10]]

random numbers from a normal distribution:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]


**12. Practical Application: Matrix Operations**

Task:

Given two matrices representing some data, perform the following operations:
- Compute the element-wise multiplication (Hadamard product) of the matrices.
- Compute the matrix multiplication (dot product) of the matrices.
- Find the transpose of one of the matrices.
- Add a new column or row to the matrix (homogeneous coordinates).


In [217]:
a = np.array([[5,7,9],
              [3,6,7],
              [1,5,7]])

b = np.array([[12,45,78],
              [11,15,17],
              [61,90,87]])

#Compute the element-wise multiplication (Hadamard product) of the matrices.
ele_wise_mult = a*b
print("element-wise multiplication (Hadamard product) of the matrices:\n",ele_wise_mult)

#Compute the matrix multiplication (dot product) of the matrices.
a1 = np.array([[5,7,9],
              [3,6,7],
              [1,5,7]])

b1 = np.array([[12,45,78],
              [11,15,17],
              [61,90,87],
              [22,5,78]])

#Transpose b1 4x3 to 3x4
b1_trans = np.transpose(b1)
dot_product = np.dot(a1,b1_trans)
print("\ndot_product:\n",dot_product)

# Add a new column (homogeneous coordinate column of ones)
a_homogeneous = np.hstack([a, np.ones((a.shape[0], 1))])
# Print the result
print("\nMatrix with an added column for homogeneous coordinates:")

#convert to int dtype
a_homogeneous = a_homogeneous.astype(int)
print(a_homogeneous)

element-wise multiplication (Hadamard product) of the matrices:
 [[ 60 315 702]
 [ 33  90 119]
 [ 61 450 609]]

dot_product:
 [[1077  313 1718  847]
 [ 852  242 1332  642]
 [ 783  205 1120  593]]

Matrix with an added column for homogeneous coordinates:
[[5 7 9 1]
 [3 6 7 1]
 [1 5 7 1]]


**13. Working with Dates and Time**

Task:

- Create an array of dates starting from a specific date and with a specific frequency (e.g., daily).
- Perform arithmetic operations on the dates, such as adding a certain number of days to each date.
- Calculate the difference between two dates.

In [225]:
#Create an array of dates starting from a specific date and with a specific frequency (e.g., daily).
# Define the start date and the number of periods (dates)
start_date = np.datetime64("2024-10-01")
num_period = 10

# Generate an array of dates with a daily frequency
date_range = start_date + np.arange(num_period)
# Print the result
print("Array of dates starting from", start_date, ":")
print(date_range)

Array of dates starting from 2024-10-01 :
['2024-10-01' '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-05'
 '2024-10-06' '2024-10-07' '2024-10-08' '2024-10-09' '2024-10-10']
